on:
  pull_request:
    paths:
    - 'stacks/**/deploy.sh'
   
jobs:
  env:
     DEPLOY_PATH: ${{ curl -sS https://api.github.com/repos/arosales/marketplace-kubernetes/pulls/${{ github.event.pull_request.number }}/files |  jq  -r '.[] | .filename' }}

  build:
    name: DOk8s deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: list file directories in current working dir
      run: ls -l
  
    - name: pwd
      run: pwd

    - name: git version
      run: git branch
      
    - name: GitSHA
      run: echo $GITHUB_SHA
      
    - name: confirm the new/updated stack deploy path
      run: echo $DEPLOY_PATH

    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show actions-example > $GITHUB_WORKSPACE/.kubeconfig

    - name: Deploy to DigitalOcean Kubernetes
      run: sh $DEPLOY_PATH

    - name: Verify deployment
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig rollout status -n kube-system deployment/metrics-server
